spring:
  application:
    name: GatewayServer
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # 모든 경로에 대해 CORS 설정 적용
            allowedOrigins: "http://localhost:3000"  # React 애플리케이션의 URL로 설정
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: first-service
          uri: lb://SERVICE01
          predicates:
            - Path=/tiger/**
        - id: second-service
          uri: lb://SERVICE02
          predicates:
            - Path=/lion/**
        - id: service01-actuator
          uri: lb://SERVICE01
          predicates:
            - Path=/actuator/**
        - id: service01-tiger2
          uri: lb://SERVICE01
          predicates:
            - Path=/tiger2/**
        - id: hospital-service
          uri: lb://HospitalService
          predicates:
            - Path=/hospitals/**
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765